import logging
from pathlib import Path
from typing import List, Dict, Any
import kuzu

_VALID_ENTITY_TYPES = frozenset({"Vehicle", "Pedestrian", "Infrastructure"})
log = logging.getLogger(__name__)

class GraphClient:
    """
    Manages the spatiotemporal relationship graph.
    Uses Kùzu, an embedded, purely local graph database (the 'DuckDB of graphs'),
    which saves directly to the data/graph_storage folder without needing a server.
    """
    def __init__(self, db_path: str = "data/graph_storage/traffic_graph"):
        # Ensure the data directory exists based on your VS Code structure
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        
        # Initialize embedded database and connection
        self.db = kuzu.Database(db_path)
        self.conn = kuzu.Connection(self.db)
        self._initialize_schema()

    def _initialize_schema(self):
        """
        Creates the graph schema using Cypher.

        Node tables:
          Vehicle, Pedestrian, Infrastructure — typed for class-filtered queries.

        Relationship tables:
          INTERACTS_WITH — cross-entity interactions with physics pointer.
          PRECEDES       — same-vehicle temporal continuity across time windows.
                           Enables "what did Vehicle 4 do before this event?"
                           queries via Cypher path traversal.
        """
        for node_type in ("Vehicle", "Pedestrian", "Infrastructure"):
            try:
                self.conn.execute(
                    f"CREATE NODE TABLE {node_type} (name STRING, PRIMARY KEY (name))"
                )
            except RuntimeError:
                pass  # Already exists

        try:
            self.conn.execute("""
                CREATE REL TABLE INTERACTS_WITH (
                    FROM Vehicle TO Vehicle,
                    FROM Vehicle TO Pedestrian,
                    FROM Vehicle TO Infrastructure,
                    FROM Pedestrian TO Vehicle,
                    FROM Pedestrian TO Pedestrian,
                    FROM Pedestrian TO Infrastructure,
                    FROM Infrastructure TO Vehicle,
                    FROM Infrastructure TO Pedestrian,
                    FROM Infrastructure TO Infrastructure,
                    predicate STRING,
                    timestamp DOUBLE,
                    trajectory_time_window STRING
                )
            """)
        except RuntimeError:
            pass  # Already exists

        # PRECEDES: temporal continuity edge on the same vehicle node.
        # Self-edge (Vehicle → Vehicle with the same name) linking consecutive
        # time windows. Properties encode which windows are connected and how
        # much time elapsed between them, enabling temporal path queries:
        #
        #   MATCH (v:Vehicle {name:'Vehicle 4'})-[r:PRECEDES*1..4]->(v2)
        #   RETURN r.from_window, r.to_window ORDER BY r.from_window
        try:
            self.conn.execute("""
                CREATE REL TABLE PRECEDES (
                    FROM Vehicle TO Vehicle,
                    FROM Pedestrian TO Pedestrian,
                    from_window    STRING,
                    to_window      STRING,
                    gap_seconds    DOUBLE
                )
            """)
        except RuntimeError:
            pass  # Already exists

    def _upsert_entity(self, entity_name: str, entity_type: str):
        """
        Inserts a typed node only if it doesn't already exist.
        entity_type must be one of the _VALID_ENTITY_TYPES; defaults to 'Vehicle'.
        """
        if entity_type not in _VALID_ENTITY_TYPES:
            entity_type = "Vehicle"
        # Node label is injected via f-string — safe because it comes from the validated frozenset.
        query = f"MERGE (e:{entity_type} {{name: $name}})"
        self.conn.execute(query, parameters={"name": entity_name})

    def insert_vlm_triples(self, triples: List[Dict[str, Any]], time_window: str):
        """
        Ingests the Subject-Predicate-Object JSON list generated by vlm_inference.py.
        
        Args:
            triples: e.g., [{"subject": "Vehicle 4", "predicate": "tailgating", "object": "Vehicle 9", "timestamp": 10.5}]
            time_window: The temporal pointer (e.g., "10.0-15.0") used by the Agent to query DuckDB later.
        """
        if not triples:
            return

        for triple in triples:
            subject_name = str(triple.get("subject", "")).strip()
            predicate_desc = str(triple.get("predicate", "")).strip()
            object_name = str(triple.get("object", "")).strip()
            timestamp = float(triple.get("timestamp", 0.0))

            # Sanitize entity types against the valid frozenset (safe for f-string injection)
            subject_type = triple.get("subject_type", "Vehicle")
            object_type = triple.get("object_type", "Vehicle")
            if subject_type not in _VALID_ENTITY_TYPES:
                subject_type = "Vehicle"
            if object_type not in _VALID_ENTITY_TYPES:
                object_type = "Vehicle"

            if not subject_name or not object_name:
                continue

            # 1. Ensure both nodes exist in their respective typed tables
            self._upsert_entity(subject_name, subject_type)
            self._upsert_entity(object_name, object_type)

            # 2. Create the directed interaction edge with physics pointers.
            # Node labels come from the validated frozenset, not from user input.
            edge_query = f"""
                MATCH (s:{subject_type} {{name: $subject}}), (o:{object_type} {{name: $object}})
                CREATE (s)-[:INTERACTS_WITH {{predicate: $pred, timestamp: $ts, trajectory_time_window: $window}}]->(o)
            """
            self.conn.execute(
                edge_query,
                parameters={
                    "subject": subject_name,
                    "object": object_name,
                    "pred": predicate_desc,
                    "ts": timestamp,
                    "window": time_window
                }
            )

    def insert_temporal_edges(
        self,
        vehicle_ids: List[int],
        prev_window: str,
        curr_window: str,
        gap_seconds: float,
    ) -> None:
        """
        Creates PRECEDES self-edges for vehicles present in two consecutive
        time windows, encoding temporal continuity.

        Called in the macro-loop after every successful VLM inference so
        that every vehicle's trajectory is linked window-by-window through
        the graph.

        Example Cypher enabled by these edges:
          -- "What was Vehicle 4 doing 10 seconds before the crash?"
          MATCH (v:Vehicle {name:'Vehicle 4'})-[r:PRECEDES*1..3]->(v2)
          WHERE r[-1].to_window = '10.0-15.0'
          RETURN r[*].from_window, r[*].to_window

        Args:
            vehicle_ids: Integer track IDs of vehicles active in both windows.
            prev_window: Time-window string of the previous macro-loop tick
                         (e.g. "5.0-10.0").
            curr_window: Time-window string of the current macro-loop tick
                         (e.g. "10.0-15.0").
            gap_seconds: Elapsed real time between the two windows (seconds).
        """
        for vid in vehicle_ids:
            name = f"Vehicle {vid}"
            self._upsert_entity(name, "Vehicle")
            try:
                self.conn.execute(
                    """
                    MATCH (v:Vehicle {name: $name})
                    CREATE (v)-[:PRECEDES {
                        from_window:  $from_w,
                        to_window:    $to_w,
                        gap_seconds:  $gap
                    }]->(v)
                    """,
                    parameters={
                        "name":   name,
                        "from_w": prev_window,
                        "to_w":   curr_window,
                        "gap":    gap_seconds,
                    },
                )
            except Exception as exc:
                log.warning("PRECEDES edge failed for %s: %s", name, exc)

    def query_graph(self, cypher_query: str) -> List[Dict[str, Any]]:
        """
        Tool for the LangGraph Agent: Executes an autonomous Cypher query 
        generated by the LLM to traverse the graph and find relationships.
        """
        try:
            # Execute the query
            result = self.conn.execute(cypher_query)
            
            # Convert Kuzu's result object into a standard Python list of dictionaries
            columns = result.get_column_names()
            records = []
            while result.has_next():
                row = result.get_next()
                records.append(dict(zip(columns, row)))
                
            return records
            
        except Exception as e:
            return [{"error": f"Graph query failed: {str(e)}"}]

    def close(self):
        """Safely closes the database connection."""
        self.conn.close()